name: Docker delivery

on:
  workflow_dispatch:
  
permissions:
  packages: read

jobs:    
  delivery:
    secrets: inherit
    uses: bitomic/utilities/.github/workflows/docker-deploy.yml@31efda957426e62e487fcc0ae79a7bd3aec3c874
