name: Docker delivery

on:
  workflow_dispatch:
  
permissions:
  packages: read

jobs:    
  delivery:
    secrets: inherit
    uses: bitomic/utilities/.github/workflows/docker-deploy.yml@79394997bd793ba79b61f77805184861350f6d46
